[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "16.15.0" }
 
[dev]
 command = "npm run dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nextjs"